Add algorithms folder.
em3ly/axon_training pull request #1
Opened 2019-04-30 17:53 UTC by cmpeguerog

- Update solution for "D - Points in Rectangle" problem.

2019-04-30 18:02 UTC, em3ly requested changes
Could you please update the folder structure for your solutions?  folder A, folder B, etc.
You might want to check red_maple structure.

2019-04-30 22:31 UTC, em3ly commented
Not sure why we need an Algorithms folder or the CMakeLists. I took a look at them and are diferents to how I implement it, for example: I use 0-index FT and OOP. Also, the idea of this repo is to share solutions, maybe at some point we might agree on general styles for specific algorithms, but in my opinion its to early for that.

2019-05-01 02:43 UTC, em3ly commented
Ok with the algorithms folder. I also think that we should structure it better and follow some rules (will be defined later), but as a start it's a good idea, so I will approve it but will be refactored in a future.

2019-05-01 02:43 UTC, em3ly approved these changes

2019-05-01 05:38 UTC, jorgedftrl approved these changes

2019-05-01 05:38 UTC, jorgedftrl commented on Algorithms/Fenwick.cpp
> +//
Approving for now, but this should be slightly refactored to be more reusable/portable

2019-05-01 05:38 UTC, jorgedftrl commented on Algorithms/Fenwick2d.cpp
> +#include <bits/stdc++.h>
Ditto

2019-05-01 05:38 UTC, jorgedftrl commented on Cracking Fenwick Tree to the root V1/Solutions/cmpeguerog/D - Points in Rectangle/Points in Rectangle.cpp
> +#include <bits/stdc++.h>
It would be nice if everybody use the same convention, e.g. problem  folder should match [A-Z]{1,2} or something similar

2019-05-01 05:41 UTC, merged